apiVersion: v1
kind: ConfigMap
metadata:
  name: http-configmap-0.0.1
  namespace: deviceshifu
data:
  #    device name and image address
  driverProperties: |
    driverSku: HTTP Device
    driverImage: http-device:v0.0.1
  #    available instructions
  instructions: |
    instructions:
      allData:
  #    telemetry retrieval methods
  #    in this example, a device_health telemetry is collected by calling hello instruction every 1 second
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 6000
      telemetryTimeoutInMilliseconds: 3000
    telemetries:
      ThingsPanel:
        properties:
          instruction: allData
          pushSettings:
           telemetryCollectionService: push-endpoint
